"""rename department

Revision ID: 2d7a5f64ec74
Revises: 74c01a1ba2d0
Create Date: 2024-06-17 23:09:54.108012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d7a5f64ec74'
down_revision = '74c01a1ba2d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department', 'departments')
    # ### end Alembic commands ###
